### ISSUE TITLE
Explain Markdown

### ISSUE THREAD

**Issue by camerican** [camerican/demo#4]
# This is a large heading like an h1
#### h4

---

Just some **bold** text here.

``` css
div.select {
  width: 100px;
}
```

| Team | City |
| --- | --- |
| Mets | New York |
| Nats | Washington, DC |
| Angels | Los Angeles |
- [ ] Checkbox list
- [x] This one is checked
- [ ] Do this thing..
